name: Dependabot Automerge

on:
  pull_request:
    branches: [master]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Wait for status checks
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.8.0
        with:
          ignoreActions: worker,WIP
          checkInterval: 60
          timeout: 1800
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Automerge
        uses: pascalgn/automerge-action@v0.16.4
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_LABELS: ''
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_DELETE_BRANCH: true
